import fmale from '../images/fmale.jpg' 
import male from '../images/male.jpg'
const doctor = [
  {
    id: 1,
    name: 'Dr. Sarah Smith',
    specialty: 'Cardiology',
    languages: {
      EN: 'English',
      FR: 'French',
    },
    nationality: 'American',
    experience: '15 years',
    urlImage: male ,
  },
  {
    id: 2,
    name: 'Dr. Ahmed Hassan',
    specialty: 'Pediatrics',
    languages: {
      AR: 'Arabic',
      EN: 'English',
    },
    nationality: 'Egyptian',
    experience: '12 years',
    urlImage:  male ,
  },
  {
    id: 3,
    name: 'Dr. James Johnson',
    specialty: 'Orthopedics',
    languages: {
      EN: 'English',
    },
    nationality: 'Canadian',
    experience: '18 years',
    urlImage: male ,
  },
  {
    id: 4,
    name: 'Dr. Fatima Ahmed',
    specialty: 'Oncology',
    languages: {
      AR: 'Arabic',
      EN: 'English',
    },
    nationality: 'Saudi Arabian',
    experience: '20 years',
    urlImage:  fmale ,
  },
  {
    id: 5,
    name: 'Dr. Thomas Baker',
    specialty: 'Neurology',
    languages: {
      EN: 'English',
      DE: 'German',
    },
    nationality: 'German',
    experience: '14 years',
    urlImage:  male ,
  },
  {
    id: 6,
    name: 'Dr. Sophia Lee',
    specialty: 'Gynecology',
    languages: {
      EN: 'English',
      KO: 'Korean',
    },
    nationality: 'South Korean',
    experience: '16 years',
    urlImage: fmale ,
  },
  {
    id: 7,
    name: 'Dr. Mohamed Abdi',
    specialty: 'Emergency Medicine',
    languages: {
      EN: 'English',
      SO: 'Somali',
    },
    nationality: 'Somali',
    experience: '10 years',
    urlImage:  male ,
  },
  {
    id: 8,
    name: 'Dr. Anna Kowalski',
    specialty: 'Psychiatry',
    languages: {
      EN: 'English',
      PL: 'Polish',
    },
    nationality: 'Polish',
    experience: '12 years',
    urlImage:  fmale ,
  },
  {
    id: 9,
    name: 'Dr. Carlos Ramirez',
    specialty: 'Internal Medicine',
    languages: {
      EN: 'English',
      ES: 'Spanish',
    },
    nationality: 'Spanish',
    experience: '17 years',
    urlImage:  male ,
  },
  {
    id: 10,
    name: 'Dr. Mei Ling',
    specialty: 'Endocrinology',
    languages: {
      EN: 'English',
      ZH: 'Mandarin',
    },
    nationality: 'Chinese',
    experience: '13 years',
    urlImage:  fmale ,
  },
  {
    id: 11,
    name: 'Dr. Ali Khan',
    specialty: 'Urology',
    languages: {
      EN: 'English',
      UR: 'Urdu',
    },
    nationality: 'Pakistani',
    experience: '15 years',
    urlImage:  male ,
  },
  {
    id: 12,
    name: 'Dr. Emily White',
    specialty: 'Pulmonology',
    languages: {
      EN: 'English',
    },
    nationality: 'Australian',
    experience: '11 years',
    urlImage:  fmale ,
  },
  {
    id: 13,
    name: 'Dr. Ahmed Salah',
    specialty: 'Ophthalmology',
    languages: {
      EN: 'English',
      AR: 'Arabic',
    },
    nationality: 'Emirati',
    experience: '19 years',
    urlImage:  male ,
  },
  {
    id: 14,
    name: 'Dr. Isabella Rossi',
    specialty: 'Rheumatology',
    languages: {
      EN: 'English',
      IT: 'Italian',
    },
    nationality: 'Italian',
    experience: '14 years',
    urlImage:  fmale ,
  },
  {
    id: 15,
    name: 'Dr. Juan Martinez',
    specialty: 'Gastroenterology',
    languages: {
      EN: 'English',
      ES: 'Spanish',
    },
    nationality: 'Mexican',
    experience: '16 years',
    urlImage:  male ,
  },
  {
    id: 16,
    name: 'Dr. Aisha Khan',
    specialty: 'Nephrology',
    languages: {
      EN: 'English',
      UR: 'Urdu',
    },
    nationality: 'Indian',
    experience: '18 years',
    urlImage:  fmale ,
  },
  {
    id: 17,
    name: 'Dr. David Johnson',
    specialty: 'Dentistry',
    languages: {
      EN: 'English',
      ES: 'Spanish',
    },
    nationality: 'American',
    experience: '20 years',
    urlImage:  male ,
  },
  {
    id: 18,
    name: 'Dr. Amira El-Masry',
    specialty: 'Oncology',
    languages: {
      EN: 'English',
      AR: 'Arabic',
    },
    nationality: 'Egyptian',
    experience: '15 years',
    urlImage:  fmale ,
  },
  {
    id: 19,
    name: 'Dr. Michael Brown',
    specialty: 'Dermatology',
    languages: {
      EN: 'English',
    },
    nationality: 'British',
    experience: '12 years',
    urlImage:  male ,
  },
  {
    id: 20,
    name: 'Dr. Hannah Kim',
    specialty: 'Otolaryngology (ENT)',
    languages: {
      EN: 'English',
      KO: 'Korean',
    },
    nationality: 'South Korean',
    experience: '14 years',
    urlImage:  fmale ,
  },
];

export default doctor; 